/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Simple autogenerated sidebars like ai-on-eks
  docs: [
    'intro',
    { type: 'autogenerated', dirName: 'performance-networking' },
    { type: 'autogenerated', dirName: 'observability-monitoring' },
    { type: 'autogenerated', dirName: 'genai-aiml' },
    { type: 'autogenerated', dirName: 'hybrid-multicloud' },
    { type: 'autogenerated', dirName: 'security-compliance' },
  ],
};

module.exports = sidebars;
