/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main documentation sidebar with all domains
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 Performance & Networking',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'performance-networking',
        },
      ],
    },
    {
      type: 'category',
      label: '👁️ Observability & Monitoring',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'observability-monitoring',
        },
      ],
    },
    {
      type: 'category',
      label: '🤖 GenAI & AI/ML',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'genai-aiml',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 Hybrid & Multi-Cloud',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'hybrid-multicloud',
        },
      ],
    },
    {
      type: 'category',
      label: '🔒 Security & Compliance',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'security-compliance',
        },
      ],
    },
    {
      type: 'category',
      label: '☁️ AWS Services',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'aws',
        },
      ],
    },
  ],

  // Domain-specific sidebars for focused navigation
  performanceNetworkingSidebar: [
    'performance-networking/README',
    {
      type: 'autogenerated',
      dirName: 'performance-networking',
    },
    {
      type: 'category',
      label: '🔗 Related Topics',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: '👁️ Network Monitoring',
          href: '/docs/observability-monitoring',
        },
        {
          type: 'link',
          label: '🔒 Network Security',
          href: '/docs/security-compliance',
        },
      ],
    },
  ],

  observabilityMonitoringSidebar: [
    'observability-monitoring/README',
    {
      type: 'autogenerated',
      dirName: 'observability-monitoring',
    },
    {
      type: 'category',
      label: '🔗 Related Topics',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: '🚀 Performance Monitoring',
          href: '/docs/performance-networking',
        },
        {
          type: 'link',
          label: '🤖 AI/ML Monitoring',
          href: '/docs/genai-aiml',
        },
      ],
    },
  ],

  genaiAimlSidebar: [
    'genai-aiml/README',
    {
      type: 'autogenerated',
      dirName: 'genai-aiml',
    },
    {
      type: 'category',
      label: '🔗 Related Topics',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: '👁️ AI/ML Monitoring',
          href: '/docs/observability-monitoring',
        },
        {
          type: 'link',
          label: '🚀 GPU Performance',
          href: '/docs/performance-networking',
        },
      ],
    },
  ],

  hybridMulticloudSidebar: [
    'hybrid-multicloud/README',
    {
      type: 'autogenerated',
      dirName: 'hybrid-multicloud',
    },
    {
      type: 'category',
      label: '🔗 Related Topics',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: '🔒 Multi-Cloud Security',
          href: '/docs/security-compliance',
        },
        {
          type: 'link',
          label: '🚀 Cross-Cloud Networking',
          href: '/docs/performance-networking',
        },
      ],
    },
  ],

  securityComplianceSidebar: [
    'security-compliance/README',
    {
      type: 'autogenerated',
      dirName: 'security-compliance',
    },
    {
      type: 'category',
      label: '🔗 Related Topics',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: '🚀 Network Security',
          href: '/docs/performance-networking',
        },
        {
          type: 'link',
          label: '👁️ Security Monitoring',
          href: '/docs/observability-monitoring',
        },
      ],
    },
  ],
};

export default sidebars;