apiVersion: v1
kind: Namespace
metadata:
  name: bench
---
# iperf3 server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  namespace: bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      nodeSelector:
        role: benchmark
      terminationGracePeriodSeconds: 0
      containers:
        - name: iperf3
          image: networkstatic/iperf3:latest
          command: ["iperf3", "-s"]
          ports:
            - containerPort: 5201
          resources:
            requests:
              cpu: "2"
              memory: "256Mi"
            limits:
              cpu: "3"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: bench
spec:
  selector:
    app: iperf3-server
  ports:
    - port: 5201
      targetPort: 5201
---
# iperf3 client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
  namespace: bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      nodeSelector:
        role: benchmark
      terminationGracePeriodSeconds: 0
      containers:
        - name: iperf3
          image: networkstatic/iperf3:latest
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: "2"
              memory: "256Mi"
            limits:
              cpu: "3"
              memory: "512Mi"
---
# httpbin echo server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: bench
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      nodeSelector:
        role: benchmark
      terminationGracePeriodSeconds: 0
      containers:
        - name: httpbin
          image: kong/httpbin:0.1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: bench
spec:
  selector:
    app: httpbin
  ports:
    - port: 80
      targetPort: 80
---
# Fortio load generator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  namespace: bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      nodeSelector:
        role: benchmark
      terminationGracePeriodSeconds: 0
      containers:
        - name: fortio
          image: fortio/fortio:1.65.0
          command: ["fortio", "server", "-http-port", "8080"]
          resources:
            requests:
              cpu: "2"
              memory: "512Mi"
            limits:
              cpu: "3"
              memory: "1Gi"
